### ISSUE TITLE
A server responds with a 500 error when a configuration file includes a response that is not formatted in JSON

### ISSUE THREAD

**Issue by ssakane123** [ssakane123/test-server#1]
# Overview

When a configuration file contains a response that is not formatted in JSON, despite having 'application/json' specified in the Content-Type header, the server responds with a 500 error.

# Example

Here is an example confirming that the server responds with a 500 error when the settings described in the Overview are applied.

First, create the following configuration file:

```yaml
host: localhost
port: 8080
- path: /notFormattedInJson
  statusCode: 200
  response: "This is not formatted in JSON"
  headers:
    Content-Type:
    - application/json
```

Second, run a server with the configuration file and request the server with the path, /notFormattedInJson:

```shell
$ curl -w 'Status Code: %{http_code}\nContent-Type: %{content_type}' http://localhost:8080/notFormattedInJson
{"Offset":1}null
Status Code: 500
Content-Type:application/json
```

By the way, a server responds an expected response when a configuration file contains a response that is formatted in JSON, despite having 'text/plain' specified in the Content-Type header.

For example, create the following configuration file:

```yaml
host: localhost
port: 8080
- path: /formattedInJson
  statusCode: 200
  response: |
    {
      "message": "hello"
    }
  headers:
    Content-Type:
    - text/plain
```

Run a server using the configuration file and request the server with the path, /formattedInJson:

```shell
$ curl -w 'Status Code:%{http_code}\nContent-Type: %{content_type}' http://localhost:8080/formattedInJson
{
  "message": "hello"
}
Status Code: 200
Content-Type: text/plain
```
